1:
  name: "Galactic Shimmer"
  price: "80.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
  options:
    -
      name: "option is cheap"
      price: "0.00"
    -
      name: "option is expensive"
      price: "0.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: ""
  image: /assets/images/neck1.png
  background: "#C4F9DDAA"
2:
  name: "Flying Smiley"
  price: "150.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: ""
  image: /assets/images/neck2.png
  background: "#F9C4DEAA"
3:
  name: "Turquoise Beech"
  price: "90.00"
  sizes:
    -
      size: 15.5
      price: "0.00"
    -
      size: 17.5
      price: "5.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: "This beauty has showstoping blue greenish turquoise biwa pearls, reminding us of dreamy skies, sea salts, and beachy good times. It is the combination of colour and shape of this pearl which make it difficult to source and a unique piece to add to your collecion. The necklace is available in several lengths, whether you are looking for a longer length layering piece or shorter more elegant stye choker - we gothcu."
  image: /assets/images/neck3.png
  background: "#F9F8C4AA"
4:
  name: "Colour is Good Classic"
  price: "80.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
  options:
    -
      name: "mathca"
      price: "0.00"
    -
      name: "teddy"
      price: "0.00"
    -
      name: "seaglass"
      price: "0.00"
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Semi-precious gemstones"
    - "Glass beads"
  details: "all necklaces contain:
  - AAA freshwater pearls
  - Tarnish resistant silver plated wire
  - Sterling silver or gold filled findings
  - Semi-precious gemstones
  - Glass beads

  Matcha features:
  - jade
  - hemimorphite
  - turquoise pearl

  Teddy features:
  - garnet (diamond shaped)
  - pink/purple pearls 

  Seaglass features:
  - apatite
  - jade"
  image: /assets/images/neck4.png
  background: "#CEFBFDAA"
5:
  name: "Peachy Meadows"
  price: "90.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
  options:
    -
      name: "bunny"
      price: "3"
    -
      name: "flowers"
      price: "5"
    -
      name: "bunny and flowers"
      price: "8"
    -
      name: "plain"
      price: "0.00"
  details: "Springtime feels all year round! Choose your length and if you want a bunny friend, flowers, or, aint no shame in plain."
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  image: /assets/images/neck1.png
  background: "#F9E4C4AA"
6:
  name: "Constallation Zebra"
  price: "95.00"
  details: "Necklace measures aprrox. 17\"" 
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Abalone shell star"
  image: /assets/images/neck1.png
  background: "#F9E4C4AA"
7:
  name: "Fierce Heart"
  price: "80.00"
  details: "Necklace measures aprrox. 15\""
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  image: /assets/images/neck1.png
  background: "#F9E4C4AA"
8:
  name: "Angel Wing"
  price: "110.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  details: ""
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  image: /assets/images/neck1.png
  background: "#F9E4C4AA"
9:
  name: "Angel Wings"
  price: "120.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  details: ""
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  image: /assets/images/neck1.png
  background: "#F9E4C4AA"