1:
  name: "Colour is Good Classic"
  necklace: True
  price: "95.00"
  sold_out: False
  sizes:
    -
      value: 15
      price: "0.00"
    -
      value: 16
      price: "5.00"
    -
      value: 17
      price: "10.00"
    -
      value: 18
      price: "15.00"
  styles:
    -
      value: "matcha"
      price: "0.00"
    -
      value: "teddy"
      price: "0.00"
    -
      value: "seaglass"
      price: "0.00"
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Semi-precious gemstones; MATCHA features jade & hemimorphite, TEDDY features garnet, SEAGLASS features apatite & jade."
    - "Glass beads"
  images: 
    - 
      path: /assets/images/matcha_neck.jpg
      caption: "matcha 17\""
    -
      path: /assets/images/matcha.jpg
      caption: "matcha"
    - 
      path: /assets/images/teddy.jpg
      caption: "teddy"
    - 
      path: /assets/images/seaglass_neck.jpg
      caption: "seaglass 16\""
  background: "#CEFBFDAA"
2:
  name: "Peachy Meadows"
  necklace: True
  price: "100.00"
  sold_out: False
  sizes:
    -
      value: 15
      price: "0.00"
    -
      value: 16
      price: "5.00"
    -
      value: 17
      price: "10.00"
  styles:
    -
      value: "bunny and flowers"
      price: "8.00"
    -
      value: "plain"
      price: "0.00"
  details: "Springtime feels all year round! Choose your length and if you want a bunny friend & flowers, or, ain't no shame in plain!"
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Gemstones"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/plain_face.jpg
      caption: "plain 15\""
    -
      path: /assets/images/plain_neck.jpg
      caption: "plain 15\""
    -
      path: /assets/images/peachymeadows_plain.jpg
      caption: "plain"
    -
      path: /assets/images/peachymeadowsandfriends.jpg
      caption: "bunny & flowers"
  background: "#F9E4C4AA"
3:
  name: "Glass Ocean"
  necklace: True
  price: "90.00"
  sold_out: True
  sizes:
    -
      value: 15.5
      price: "0.00"
    -
      value: 17.5
      price: "10.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: "This beauty has showstoping blue greenish turquoise biwa pearls, reminding us of dreamy skies, sea salts, and beachy good times. It is the combination of colour and shape of this pearl which make it difficult to source and a unique piece to add to your collecion. The necklace is available in two lengths, whether you are looking for a longer layering piece or shorter more elegant stye choker - we gotchu."
  images: 
    - 
      path: /assets/images/beech.jpg
      caption: ""
    -
      path: /assets/images/turquoise_face.jpg
      caption: ""
  background: "#F9F8C4AA"
4:
  name: "Pearly"
  necklace: False
  price: "20.00"
  sold_out: True
  sizes:
    -
      value: 4
      price: "0.00"
    -
      value: 5
      price: "0.00"
    -
      value: 6
      price: "0.00"
    -
      value: 7
      price: "0.00"
    -
      value: 8
      price: "0.00"
  styles:
    -
      value: "pearly"
      price: "0.00"
  details: "<b>Currently only shipping within Canada, Limited Stock!</b><br> These styles of ring are made with stetchy string.</br>PEARLY stretches up to 2 sizes</br>Due to the irregular shape of the pearls, ring size can not be exact and are an approximation."
  materials:
    - "AAA freshwater pearls"
    - "Stretchy string"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/pearly.png
      caption: "pearly"
  background: "#F9E4C4AA"
5:
  name: "Galactic Shimmer"
  necklace: True
  price: "80.00"
  sold_out: False
  sizes:
    -
      value: 15
      price: "0.00"
    -
      value: 16
      price: "5.00"
    -
      value: 17
      price: "10.00"
    -
      value: 18
      price: "15.00"
  materials: 
    - "Grey silver rainbow AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: ""
  images:
    - 
      path: /assets/images/galacticshimmer_face.jpg
      caption: "16 \""
    - 
      path: /assets/images/galacticshimmer.jpg
      caption: ""
  background: "#C4F9DDAA"
6:
  name: "Tentacle Thangz"
  necklace: False
  price: "15.00"
  sold_out: False
  sizes:
    -
      value: "4-6 (stretch string)" 
      price: "0.00"
    -
      value: "7-8 (stretch string)"
      price: "0.00"
    - 
      value: "9-10 (stretch string)"
      price: "0.00"
  styles:
    -
      value: "sea"
      price: "0.00"
    -
      value: "fuschia"
      price: "0.00"
    -
      value: "starz"
      price: "0.00"
    -
      value: "smilez"
      price: "0.00"
    -
      value: "deep space"
      price: "0.00"
  details: "<b>currently only shipping within Canada, Limited Stock!</b><br>There are different size options for these styles of rings, made with stretchy string.</br>Due to the irregular shape of the pearls, ring size can not be exact and are an approximation."
  materials:
    - "AAA freshwater pearls"
    - "Stretchy string"
    - "Glass beads"
    - "Abalone shell stars in STARZ & DEEP SPACE"
  images: 
    - 
      path: /assets/images/smileyring_face.jpg
      caption: ""
    - 
      path: /assets/images/all.jpeg
      caption: ""
    - 
      path: https://gitlab.com/colourisgood/colourisgood_website_video/-/raw/master/web/ringz.mp4
      caption: ""
      video: True
    - 
      path: https://gitlab.com/colourisgood/colourisgood_website_video/-/raw/master/web/smileyring.mp4
      caption: ""
      video: True
  background: "#F9E4C4AA"
