1:
  name: "Galactic Shimmer"
  price: "80.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
    -
      size: 18
      price: "15.00"
  options:
    -
      name: "option is cheap"
      price: "0.00"
    -
      name: "option is expensive"
      price: "0.00"
  materials: 
    - "Grey silver rainbow AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: ""
  images:
    - 
      path: /assets/images/galacticshimmer_face.jpg
      caption: ""
    - 
      path: /assets/images/galacticshimmer.jpg
      caption: ""
    - 
      path: video
      caption: ""
  background: "#C4F9DDAA"
2:
  name: "Flying Smiley"
  price: "150.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Ceramic smiley bead"
  details: ""
  images: 
    - 
      path: /assets/images/flyingsmiley.jpg
      caption: ""
  background: "#F9C4DEAA"
3:
  name: "Turquoise Beech"
  price: "90.00"
  sizes:
    -
      size: 15.5
      price: "0.00"
    -
      size: 17.5
      price: "5.00"
  materials: 
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  details: "This beauty has showstoping blue greenish turquoise biwa pearls, reminding us of dreamy skies, sea salts, and beachy good times. It is the combination of colour and shape of this pearl which make it difficult to source and a unique piece to add to your collecion. The necklace is available in two lengths, whether you are looking for a longer layering piece or shorter more elegant stye choker - we gothcu."
  images: 
    - 
      path: /assets/images/beech.jpg
      caption: ""
    -
      path: /assets/images/turquoise_face.jpg
      caption: ""
  background: "#F9F8C4AA"
4:
  name: "Colour is Good Classic"
  price: "80.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
  options:
    -
      name: "matcha"
      price: "0.00"
    -
      name: "teddy"
      price: "0.00"
    -
      name: "seaglass"
      price: "0.00"
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Semi-precious gemstones; MATCHA features jade & hemimorphite, TEDDY features garnet, SEAGLASS features apatite & jade."
    - "Glass beads"
  images: 
    - 
      path: /assets/images/matcha.jpg
      caption: "mathca"
    -
      path: /assets/images/matcha_neck.jpg
      caption: "mathca"

    - 
      path: /assets/images/teddy.jpg
      caption: "teddy"
    - 
      path: /assets/images/seaglass_neck.jpg
      caption: "seaglass"
  background: "#CEFBFDAA"
5:
  name: "Peachy Meadows"
  price: "90.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
    -
      size: 17
      price: "10.00"
  options:
    -
      name: "bunny and flowers"
      price: "8.00"
    -
      name: "plain"
      price: "0.00"
  details: "Springtime feels all year round! Choose your length and if you want a bunny friend & flowers, or, ain't no shame in plain!"
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Gemstones"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/plain_face.jpg
      caption: "plain"
    -
      path: /assets/images/plain_neck.jpg
      caption: "plain"
    -
      path: /assets/images/peachymeadows_plain.jpg
      caption: "plain"
    -
      path: /assets/images/peachymeadowsandfriends.jpg
      caption: "bunny & flowers"
  background: "#F9E4C4AA"
6:
  name: "Constallation Zebra"
  price: "95.00"
  details: "Necklace measures aprrox. 17\"" 
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Abalone shell star"
    - "Ceramic dice"
    - "Gemstones"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/zebrastar.jpg
      caption: ""
  background: "#F9E4C4AA"
7:
  name: "Fierce Heart"
  price: "80.00"
  details: "Necklace measures aprrox. 15\""
  materials:
    - "Tiger's eye (semi-precious stone) heart bead"
    - "Ceramic Tiger"
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
    - "Gemstones"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/fierceheart.jpg
      caption: ""
  background: "#F9E4C4AA"
8:
  name: "Wing Divine"
  price: "110.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  details: ""
  materials:
    - "Aquamarine"
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  images: 
    - 
      path: /assets/images/wingdivine.jpg
      caption: ""
  background: "#F9E4C4AA"
9:
  name: "Angel WingZ"
  price: "120.00"
  sizes:
    -
      size: 15
      price: "0.00"
    -
      size: 16
      price: "5.00"
  details: ""
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Sterling silver or gold filled findings"
  images: 
    - 
      path: /assets/images/angelwingz2.jpg
      caption: ""
    - 
      path: /assets/images/angelwingz_face.jpg
      caption: ""
  background: "#F9E4C4AA"
10:
  name: "Double Rainbow Ringzz"
  price: "20.00"
  options:
    -
      name: "pearly"
      price: "0.00"
    -
      name: "unicorn"
      price: "0.00"
  details: "<b>currently only shipping within Canada</b><br>Pearly is approx. size 6<br>Unicorn is approx. size 4.5.<br> 
  Due to the irregular shape of the pearls, ring size can not be exact and are an approximation."
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Glass beads"
  images: 
    - 
      path: /assets/images/pearly.png
      caption: "pearly"
    - 
      path: /assets/images/unicorn.png
      caption: "unicorn"
  background: "#F9E4C4AA"
11:
  name: "Tentacle Thangz"
  price: "10.00"
  options:
    -
      name: "sea"
      price: "0.00"
    -
      name: "fuschia"
      price: "0.00"
    -
      name: "starz size 5"
      price: "5.00"
    -
      name: "starz size 6.5"
      price: "5.00"
    -
      name: "smilez"
      price: "5.00"
    -
      name: "deep space"
      price: "5.00"
  details: "<b>currently only shipping within Canada</b><br>SEA & FUSCHIA are approx. size 6.<br>SMILEZ are approx. size 6.<br>DEEP SPACE is approx. 6.5.<br>There are two options for STARZ, aprrox. size 5 and 6.5.<br>Due to the irregular shape of the pearls, ring size can not be exact and are an approximation."
  materials:
    - "AAA freshwater pearls"
    - "Tarnish resistant silver plated wire"
    - "Glass beads"
    - "star Abalone shell in STARZ & DEEP SPACE"
  images: 
    - 
      path: /assets/images/smileyring_face.jpg
      caption: ""
  background: "#F9E4C4AA"