1:
  name: "Hidden Jaguar"
  price: "99.99"
  details: "this is a more detailed description. this is an even longer description can we even try to be duplicate of our surrogate in the minds eye."
  image: /assets/images/neck3.jpg
2:
  name: "Sullen Dragon"
  price: "79.99"
  details: "this would be a great buy. has dragon claws"
  image: /assets/images/neck2.png
3:
  name: "Delicious Breakfast Sandwhich"
  price: "399.99"
  details: "this is expensive but worth it"
  image: /assets/images/neck3.jpg
4:
  name: "Radical Rubies"
  price: "40.99"
  details: "feast your eyes on this beauty"
  image: /assets/images/neck4.png
5:
  name: "Luxurious Floating Panda"
  price: "219.99"
  details: "your hearts tru desire"
  image: /assets/images/neck1.png